// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.27.0

package model

import (
	"database/sql"
)

type Post struct {
	ID       int64
	UserID   int64
	Title    string
	Body     sql.NullString
	Tags     sql.NullString
	UpdateAt sql.NullString
	CreateAt interface{}
}

type User struct {
	ID       int64
	Email    string
	Password string
	Name     string
	Bio      sql.NullString
	UpdateAt sql.NullString
	CreateAt sql.NullString
}
