CREATE TABLE users (
  id INTEGER PRIMARY KEY,
  email TEXT NOT NULL,
  password TEXT NOT NULL,
  name TEXT NOT NULL,
  bio TEXT,
  update_at TEXT DEFAULT CURRENT_TIMESTAMP,
  create_at TEXT DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE posts (
  id INTEGER PRIMARY KEY,
  user_id INTEGER NOT NULL,
  title TEXT NOT NULL,
  body TEXT,
  tags TEXT,
  update_at TEXT DEFAULT CURRENT_TIMESTAMP,
  create_at TEXT DEFAULT CURRENT_TIMESTAMP,
  FOREIGN KEY (user_id) REFERENCES sub_flows(id) ON DELETE CASCADE
);
